/**
 * name : common.js
 * author : Aman Karki
 * Date : 13-July-2020
 * Description : All common messages.
 */

module.exports = {
	ACTIVE_STATUS: 'active',
	PUBLISHED: 'published',
	ASSESSMENT: 'assessment',
	CONTENT: 'content',
	IMPROVEMENT_PROJECT: 'improvementProject',
	MULTIPLE: 'multiple',
	OTHERS: 'Others',
	SIMPLE_TASK_TYPE: 'simple',
	NOT_STARTED: 'not started',
	RECENTLY_ADDED_PROJECT: 'currentlyAdded',
	IMPORTANT_PROJECT: 'importantProject',
	COMPLETED_STATUS: 'completed',
	INPROGRESS_STATUS: 'inProgress',
	NOT_STARTED_STATUS: 'notStarted',
	STARTED: 'started',
	SUBMITTED_STATUS: 'submitted',
	OBSERVATION: 'observation',
	PUBLISHED_STATUS: 'published',
	LEAD_ASSESSOR: 'LEAD_ASSESSOR',
	PROJECT_DESCRIPTION:
		'Manage and track your school improvement easily, by creating tasks and planning project timelines.',
	RESOURCE_TYPE: 'Improvement Project Solution',
	ENGLISH_LANGUAGE: 'English',
	KEYWORDS: 'Improvement Project',
	ASSIGN_TO_ME: 'assignedToMe',
	CREATED_BY_ME: 'createdByMe',
	DEFAULT_PAGE_NO: 1,
	DEFAULT_PAGE_SIZE: 100,
	OBSERVATION_REFERENCE_KEY: 'observation',
	ALLOW_MULTIPLE_ASSESSMENTS: 'allowMultipleAssessemts',
	IS_RUBRIC_DRIVEN: 'isRubricDriven',
	CRITERIA_LEVEL_REPORT: 'criteriaLevelReport',
	LINK: 'link',
	DEFAULT_SUBMISSION_REQUIRED: 1,
	TASK_SEQUENCE: 'taskSequence',
	CHILDREN: 'children',
	ATTACHMENT_TYPE_LINK: 'link',
	PROJECT_ATTACHMENT: 'project',
	TASK_ATTACHMENT: 'task',
	DEFAULT_TASK_COMPLETED: 0,
	IMAGE_DATA_TYPE: 'image/jpeg',
	DISTRICT: 'district',
	SERVER_TIME_OUT: 5000,
	OK: 'OK',
	PROJECT: 'project',
	PROJECT_CERTIFICATE_GENERATED_SUCCESSFULLY: 'Certificate generated successfully',
	DISCOVERED_BY_ME: 'discoveredByMe',
	COURSE: 'course',
	SURVEY: 'survey',
	INACTIVE: 'inactive',
	ALL_ROLES: 'all',
	OFF: 'OFF',
	DEFAULT_SURVEY_REMOVED_DAY: 15,
	END_DATE: 'endDate',
	START_DATE: 'startDate',
	SCHOOL: 'school',
	INSTITUTIONAL: 'institutional',
	PREFIX_FOR_SOLUTION_LINK: 'view',
	CREATE_OBSERVATION: '/create-observation/',
	CREATE_PROJECT: '/project/',
	CREATE_SURVEY: '/create-survey/',
	SUBMISSION_STATUS_COMPLETED: 'completed',
	EXPIRED: 'expired',
	STARTED: 'started',
	AWS_SERVICE: 'AWS',
	WRITE_PERMISSION: 'w',
	READ_PERMISSION: 'r',
	PUBLIC: 'public',
	PRIVATE: 'private',
	AWS: 'aws',
	AZURE: 'azure',
	GCP: 'gcloud',
	OCI: 'oci',
	SUCCESS: 'SUCCESS',
	STATUS_FAILURE: 'FAILURE',
	PDF_REPORT_GENERATED_: 'PDF_REPORT_GENERATED_SUCCESSFULLY',
	COULD_NOT_GENERATE_PDF: 'COULD_NOT_GENERATE_PDF_REPORT',
	SOLUTION_MODEL_NAME: 'solutions',
}
